import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root layout component that provides the global HTML structure, font, and site chrome.
 *
 * Renders an <html lang="en"> element and a <body> that applies the Inter font variable and antialiasing, and that contains the Header, the supplied page content, and the Footer.
 *
 * @param children - The page content to render inside the layout
 * @returns A JSX element representing the application's root HTML structure including Header, `children`, and Footer
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}